version: "3.8"
services: # the different images that will be running as containers
  app:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "8080:8080"
    volumes: 
      - .:/root/work
